version: '3.5'

services:
  lab:
    container_name: jupyterlab
    build:
      context: .
    command: [
        'jupyter',
        'lab',
        # Set working directory as empty directory - no modified time displayed
        '--notebook-dir=./work',
        '--ServerApp.token=',
        '--ServerApp.password=',
        '--ServerApp.disable_check_xsrf=True',
        '--LabServerApp.extra_labextensions_path=/opt/labextension',
        # Workaround bug: https://github.com/ipython/traitlets/issues/668
        '--LabServerApp.extra_labextensions_path=/dev/null'
      ]
    environment:
      PYTHONPATH: /opt/serverextension
    networks:
      - frontend
    ports:
      - 8888:8888
    volumes:
      - ../../jupyterlab_git/labextension:/opt/labextension/@jupyterlab/git
      - ../..:/opt/serverextension
      - ../../jupyter-config/jupyter_server_config.d:/etc/jupyter/jupyter_server_config.d

  e2e:
    # docker must match playwright version in ui-tests/package.json
    image: mcr.microsoft.com/playwright:v1.14.0-focal
    entrypoint:
      [
        '/tmp/e2e-tests/prepare.sh',
        'jupyterlab:8888',
        '--strict',
        '--timeout=60',
        '--'
      ]
    command: ['npx', 'playwright', 'test']
    environment:
      # JupyterLab URL
      TARGET_URL: http://jupyterlab:8888
    # See https://playwright.dev/docs/docker/#run-the-image
    ipc: host
    networks:
      - frontend
    depends_on:
      - lab
    volumes:
      - .:/tmp/e2e-tests
      - ..:/opt/ui-tests
    working_dir: /opt/ui-tests

networks:
  frontend:
